package aot

import (
	"fmt"
	"go/format"
	"math"
	"strconv"
	"strings"

	"github.com/go-embedded-ruby/ruby/internal/bytecode"
	"github.com/go-embedded-ruby/ruby/internal/object"
)

// FreezeISeq returns the Go source of a self-contained file that reconstructs
// iseq — with no lexer, parser or compiler — as `func fn() *bytecode.ISeq`. It
// is how a closed-world binary embeds its program (and the prelude): the
// compiled bytecode is baked in as Go literals, so the front-end can be dropped
// from the link.
//
// pkg is the package clause; fn the constructor name; buildTag, when non-empty,
// is emitted as a `//go:build <tag>` constraint. The output is gofmt-clean (it
// is run through go/format); a formatting failure indicates a serializer bug and
// surfaces as the raw, unformatted source so the eventual build fails loudly.
//
// Only the constant kinds the compiler ever pools — Integer, Bignum, Float,
// String and Symbol — are supported; any other value type is a programming
// error and panics, since it could not have come from a real compilation.
func FreezeISeq(iseq *bytecode.ISeq, pkg, fn, buildTag string) string {
	f := &freezer{}
	var body strings.Builder
	body.WriteString("\treturn ")
	f.writeISeq(&body, iseq)
	body.WriteString("\n")

	var b strings.Builder
	b.WriteString("// Code generated by FreezeISeq; DO NOT EDIT.\n")
	if buildTag != "" {
		fmt.Fprintf(&b, "//go:build %s\n\n", buildTag)
	}
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/go-embedded-ruby/ruby/internal/bytecode\"\n")
	b.WriteString("\t\"github.com/go-embedded-ruby/ruby/internal/object\"\n")
	if f.needBig {
		b.WriteString("\t\"math/big\"\n")
	}
	if f.needMath {
		b.WriteString("\t\"math\"\n")
	}
	b.WriteString(")\n\n")

	fmt.Fprintf(&b, "func %s() *bytecode.ISeq {\n", fn)
	b.WriteString(body.String())
	b.WriteString("}\n")

	if f.needBig {
		b.WriteString("\nfunc frozenBig(s string) *big.Int {\n\ti, _ := new(big.Int).SetString(s, 10)\n\treturn i\n}\n")
	}
	if f.needMath {
		b.WriteString("\nfunc frozenFloat(bits uint64) object.Float {\n\treturn object.Float(math.Float64frombits(bits))\n}\n")
	}

	out, err := formatSource([]byte(b.String()))
	if err != nil {
		return b.String() // a syntax error here is a serializer bug; let the build fail loudly
	}
	return string(out)
}

// formatSource is a seam over go/format.Source so the format-failure fallback
// (which a correct serializer never triggers) stays testable.
var formatSource = format.Source

// freezer accumulates which optional imports/helpers the emitted source needs.
type freezer struct {
	needBig  bool
	needMath bool
}

// writeISeq emits a *bytecode.ISeq composite literal. Every field is written
// explicitly so the reconstruction is byte-for-byte the compiler's output —
// including the fields whose correct default is -1 (SplatIndex/KwRestSlot/
// BlockSlot), which a zero-valued struct would get wrong.
func (f *freezer) writeISeq(b *strings.Builder, s *bytecode.ISeq) {
	if s == nil {
		b.WriteString("nil")
		return
	}
	b.WriteString("&bytecode.ISeq{\n")
	fmt.Fprintf(b, "Name: %s,\n", strconv.Quote(s.Name))
	f.writeInsns(b, s.Insns)
	f.writeConsts(b, s.Consts)
	writeStrings(b, "Names", s.Names)
	writeStrings(b, "Params", s.Params)
	fmt.Fprintf(b, "NumRequired: %d,\n", s.NumRequired)
	fmt.Fprintf(b, "SplatIndex: %d,\n", s.SplatIndex)
	writeStrings(b, "KwNames", s.KwNames)
	writeBools(b, "KwRequired", s.KwRequired)
	fmt.Fprintf(b, "KwRestSlot: %d,\n", s.KwRestSlot)
	fmt.Fprintf(b, "BlockSlot: %d,\n", s.BlockSlot)
	fmt.Fprintf(b, "NumLocals: %d,\n", s.NumLocals)
	writeStrings(b, "Locals", s.Locals)
	f.writeChildren(b, s.Children)
	fmt.Fprintf(b, "Super: %s,\n", strconv.Quote(s.Super))
	b.WriteString("}")
}

func (f *freezer) writeInsns(b *strings.Builder, insns []bytecode.Instr) {
	if insns == nil {
		return // zero value is a nil slice
	}
	b.WriteString("Insns: []bytecode.Instr{")
	for _, in := range insns {
		writeInstr(b, in)
		b.WriteString(", ")
	}
	b.WriteString("},\n")
}

// writeInstr emits one Instr as a keyed composite literal carrying only its
// non-zero fields (keyed so `go vet` is happy; sparse so the output stays
// compact — most instructions have zero B/C).
func writeInstr(b *strings.Builder, in bytecode.Instr) {
	parts := make([]string, 0, 4)
	if in.Op != 0 {
		parts = append(parts, fmt.Sprintf("Op: %d", in.Op))
	}
	if in.A != 0 {
		parts = append(parts, fmt.Sprintf("A: %d", in.A))
	}
	if in.B != 0 {
		parts = append(parts, fmt.Sprintf("B: %d", in.B))
	}
	if in.C != 0 {
		parts = append(parts, fmt.Sprintf("C: %d", in.C))
	}
	if in.Flags != 0 {
		parts = append(parts, fmt.Sprintf("Flags: %d", in.Flags))
	}
	b.WriteString("{")
	b.WriteString(strings.Join(parts, ", "))
	b.WriteString("}")
}

func (f *freezer) writeConsts(b *strings.Builder, consts []object.Value) {
	if consts == nil {
		return
	}
	b.WriteString("Consts: []object.Value{\n")
	for _, c := range consts {
		f.writeConst(b, c)
		b.WriteString(",\n")
	}
	b.WriteString("},\n")
}

// writeConst emits one constant-pool value. The set mirrors compiler.addConst.
func (f *freezer) writeConst(b *strings.Builder, v object.Value) {
	switch c := v.(type) {
	case object.Integer:
		fmt.Fprintf(b, "object.Integer(%d)", int64(c))
	case object.Symbol:
		fmt.Fprintf(b, "object.Symbol(%s)", strconv.Quote(string(c)))
	case *object.String:
		if c.Frozen {
			fmt.Fprintf(b, "&object.String{B: []byte(%s), Frozen: true}", strconv.Quote(c.Str()))
		} else {
			fmt.Fprintf(b, "object.NewString(%s)", strconv.Quote(c.Str()))
		}
	case object.Float:
		f.needMath = true
		fmt.Fprintf(b, "frozenFloat(%#x)", math.Float64bits(float64(c)))
	case *object.Bignum:
		f.needBig = true
		fmt.Fprintf(b, "&object.Bignum{I: frozenBig(%s)}", strconv.Quote(c.I.String()))
	default:
		panic(fmt.Sprintf("aot.FreezeISeq: unsupported constant %T (not produced by the compiler)", v))
	}
}

func (f *freezer) writeChildren(b *strings.Builder, kids []*bytecode.ISeq) {
	if kids == nil {
		return
	}
	b.WriteString("Children: []*bytecode.ISeq{\n")
	for _, k := range kids {
		f.writeISeq(b, k)
		b.WriteString(",\n")
	}
	b.WriteString("},\n")
}

func writeStrings(b *strings.Builder, field string, ss []string) {
	if ss == nil {
		return
	}
	fmt.Fprintf(b, "%s: []string{", field)
	for _, s := range ss {
		fmt.Fprintf(b, "%s, ", strconv.Quote(s))
	}
	b.WriteString("},\n")
}

func writeBools(b *strings.Builder, field string, bs []bool) {
	if bs == nil {
		return
	}
	fmt.Fprintf(b, "%s: []bool{", field)
	for _, v := range bs {
		fmt.Fprintf(b, "%t, ", v)
	}
	b.WriteString("},\n")
}
