package aot

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/go-embedded-ruby/ruby/internal/bytecode"
)

// CompileProgram lowers the top-level methods of a program to a single Go source
// file (package vm) that `rbgo build` links into the binary: one function per
// compilable method plus an init() registering each with the dispatch seam
// (RegisterCompiled). Methods this stage cannot lower — and any redefinition of
// a name already taken — are skipped and left to the interpreter.
//
// It handles methods defined at the top level (owner Object); methods inside
// class/module bodies are not walked yet and remain interpreted. ok is false
// when nothing could be compiled, so the caller can build a plain binary.
func CompileProgram(top *bytecode.ISeq) (content string, keys []string, ok bool) {
	var funcs strings.Builder
	var regs strings.Builder
	seen := map[string]bool{}

	for _, in := range top.Insns {
		if in.Op != bytecode.OpDefineMethod {
			continue
		}
		name := top.Names[in.A]
		if seen[name] {
			continue // only the first definition of a name is compiled (matches deopt-on-redef)
		}
		child := top.Children[in.B]
		goName := "aotm" + strconv.Itoa(len(keys))
		// Prefer the level-3 integer-kernel specialisation; fall back to the
		// sound level-1 lowering for everything else.
		src, lowered := CompileSpecialized(child, goName, name)
		if !lowered {
			src, lowered = Compile(child, goName, name)
		}
		if !lowered {
			continue
		}
		seen[name] = true
		funcs.WriteString(src)
		funcs.WriteString("\n")
		key := "Object#" + name
		fmt.Fprintf(&regs, "\tRegisterCompiled(%q, (*VM).%s)\n", key, goName)
		keys = append(keys, key)
	}

	// Level 2: lower the top-level (`<main>`) code itself — the block-/string-/
	// array-/hash-heavy script body that defines no hot method for level-1/3 to
	// touch — to a native `aotMain`, registered so `Run` dispatches to it instead
	// of interpreting the program's top level. Independent of the per-method
	// lowering above: a program can have its methods compiled, its main compiled,
	// both, or neither.
	mainSrc, nCaches, mainOK := CompileMain(top)
	if mainOK {
		funcs.WriteString(mainSrc)
		funcs.WriteString("\n")
		for i := 0; i < nCaches; i++ {
			fmt.Fprintf(&funcs, "var aotic%d inlineCache\n", i)
		}
		regs.WriteString("\tRegisterCompiledMain((*VM).aotMain)\n")
		keys = append(keys, "<main>")
	}

	if len(keys) == 0 {
		return "", nil, false
	}

	var b strings.Builder
	b.WriteString("// Code generated by `rbgo build`; DO NOT EDIT.\n")
	b.WriteString("package vm\n\n")
	// object is always referenced (every signature is object.Value); bytecode only
	// when a lowered body emits an operator through vm.binaryOp.
	body := funcs.String()
	b.WriteString("import (\n")
	if strings.Contains(body, "bytecode.") {
		b.WriteString("\t\"github.com/go-embedded-ruby/ruby/internal/bytecode\"\n")
	}
	b.WriteString("\t\"github.com/go-embedded-ruby/ruby/internal/object\"\n")
	b.WriteString(")\n\n")
	b.WriteString(body)
	b.WriteString("func init() {\n")
	b.WriteString(regs.String())
	b.WriteString("}\n")
	return b.String(), keys, true
}
