// Copyright (c) the go-embedded-ruby/ruby authors
//
// SPDX-License-Identifier: BSD-3-Clause

package ruby

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

var updateBacking = flag.Bool("update-backing", false,
	"rewrite bench/modules/BACKING.md from what go.mod currently requires")

// Every module under bench/modules has a documentation site of its own, and each
// of those sites opens by saying that rbgo *binds* a pure-Go library for it:
//
//	go-ruby-set/set is the pure-Go library that rbgo binds for Ruby's set.
//	rbgo's number reflects this pure-Go library doing the work.
//
// That sentence is a claim about this repository, and it stops being true the
// moment a module moves in-tree. It did: #330 reimplemented Set here for MRI 4.0
// conformance, #333's go mod tidy dropped the now-unused require the next day,
// and the page in the other org went on attributing rbgo's number to a library
// rbgo no longer used — for seven weeks, and with a figure that had moved by
// 3.7x underneath it.
//
// Nothing about that trade was wrong. What was missing was anything that would
// say it had happened. This test is that: it writes down, beside the benchmark
// scripts, which of them run on an external go-ruby library and which run on
// code in this repository, and fails when the file and go.mod disagree.
//
// Regenerate with:  go test -run TestBenchmarkedModulesSayWhereTheirCodeLives -update-backing
func TestBenchmarkedModulesSayWhereTheirCodeLives(t *testing.T) {
	scripts, err := filepath.Glob(filepath.Join("bench", "modules", "*.rb"))
	if err != nil {
		t.Fatalf("listing the benchmark scripts: %v", err)
	}
	if len(scripts) == 0 {
		t.Fatal("no benchmark scripts found; this test would pass by measuring nothing")
	}

	gomod, err := os.ReadFile("go.mod")
	if err != nil {
		t.Fatalf("reading go.mod: %v", err)
	}
	required := requiredModules(string(gomod))
	// A control: the file must name modules this repository really requires, or
	// the parse is wrong and every row below would read "in-tree" for the wrong
	// reason.
	if len(required) < 50 {
		t.Fatalf("go.mod parsed to %d requirements, which cannot be right", len(required))
	}

	names := make([]string, 0, len(scripts))
	for _, s := range scripts {
		names = append(names, strings.TrimSuffix(filepath.Base(s), ".rb"))
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("<!-- Generated by TestBenchmarkedModulesSayWhereTheirCodeLives. Do not edit by hand. -->\n")
	b.WriteString("# What each benchmarked module runs on\n\n")
	b.WriteString("`bench/modules/<m>.rb` exercises Ruby's `<m>`. This says whether rbgo serves\n")
	b.WriteString("it from an external `go-ruby-<m>` library or from code in this repository —\n")
	b.WriteString("which is what the per-library documentation sites claim, and what stops being\n")
	b.WriteString("true when a module moves in-tree.\n\n")
	b.WriteString("| Module | Runs on |\n| --- | --- |\n")
	for _, m := range names {
		path := fmt.Sprintf("github.com/go-ruby-%s/%s", m, m)
		if required[path] {
			fmt.Fprintf(&b, "| %s | `%s` |\n", m, path)
		} else {
			fmt.Fprintf(&b, "| %s | **in-tree** (this repository) |\n", m)
		}
	}
	want := b.String()

	out := filepath.Join("bench", "modules", "BACKING.md")
	if *updateBacking {
		if err := os.WriteFile(out, []byte(want), 0o644); err != nil {
			t.Fatalf("writing %s: %v", out, err)
		}
		t.Logf("wrote %s", out)
		return
	}

	got, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading %s (regenerate with -update-backing): %v", out, err)
	}
	if string(got) != want {
		t.Errorf("%s no longer matches go.mod.\n\nA module has moved between an external\n"+
			"go-ruby library and this repository. Regenerate with:\n\n"+
			"    go test -run TestBenchmarkedModulesSayWhereTheirCodeLives -update-backing\n\n"+
			"and then say so wherever that module's performance is published: the page\n"+
			"in its own org opens by naming the library rbgo binds for it.\n\n%s",
			out, firstDifference(string(got), want))
	}
}

// requiredModules pulls the module paths out of go.mod's require blocks. It is
// deliberately a parse of the text rather than a call to `go list`: the test has
// to answer the same question a reader of go.mod would.
func requiredModules(gomod string) map[string]bool {
	out := map[string]bool{}
	inBlock := false
	for _, line := range strings.Split(gomod, "\n") {
		s := strings.TrimSpace(line)
		if i := strings.Index(s, "//"); i >= 0 {
			s = strings.TrimSpace(s[:i])
		}
		switch {
		case s == "require (":
			inBlock = true
			continue
		case inBlock && s == ")":
			inBlock = false
			continue
		case strings.HasPrefix(s, "require "):
			s = strings.TrimSpace(strings.TrimPrefix(s, "require "))
		case !inBlock:
			continue
		}
		if fields := strings.Fields(s); len(fields) >= 2 {
			out[fields[0]] = true
		}
	}
	return out
}

// firstDifference names the first line that differs, because a diff of a
// generated table is unreadable and the answer is always one row.
func firstDifference(got, want string) string {
	g, w := strings.Split(got, "\n"), strings.Split(want, "\n")
	for i := 0; i < len(g) || i < len(w); i++ {
		gl, wl := "", ""
		if i < len(g) {
			gl = g[i]
		}
		if i < len(w) {
			wl = w[i]
		}
		if gl != wl {
			return fmt.Sprintf("first difference at line %d:\n  file:   %q\n  go.mod: %q", i+1, gl, wl)
		}
	}
	return "(the files differ only in trailing bytes)"
}
