// Command aotgen emits AOT-compiled Ruby methods as real *VM methods into
// internal/vm/aot_e2e_gen_test.go, each paired with the reference MRI's output
// for the same program, captured at generation time. The committed driver
// (aot_e2e_test.go) runs each compiled method and diffs its result against that
// baked oracle — proving the generated Go behaves identically to the reference
// interpreter, with no ruby dependency (and no ruby-version skew) at test time.
//
// Regenerate with: go generate ./internal/vm/...  (needs MRI ruby on the host).
package main

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/go-embedded-ruby/ruby/internal/aot"
	"github.com/go-embedded-ruby/ruby/internal/compiler"
	"github.com/go-embedded-ruby/ruby/internal/parser"
)

// referenceRubyCandidates is the oracle whose output is baked into the cases.
var referenceRubyCandidates = []string{"/opt/homebrew/opt/ruby/bin/ruby", "ruby"}

// mriOutput runs prog through the reference MRI and returns its trimmed stdout.
func mriOutput(prog string) string {
	var ruby string
	for _, c := range referenceRubyCandidates {
		if p, err := exec.LookPath(c); err == nil {
			ruby = p
			break
		}
	}
	if ruby == "" {
		fail("reference ruby not found; cannot bake oracle output (MRI is required to regenerate)")
	}
	cmd := exec.Command(ruby, "-e", prog)
	cmd.Env = append(os.Environ(), "RUBYOPT=")
	out, err := cmd.Output()
	if err != nil {
		fail("MRI failed on %q: %v", prog, err)
	}
	return strings.TrimRight(string(out), "\n")
}

// a case: a Ruby method `m` (or `fib`), the Go name to compile it under, the
// Ruby method name (for self-recursion lowering), and the literal call args.
type aotCase struct {
	goName, rubyName, def, args string
}

var cases = []aotCase{
	{"e2eArith", "m", "def m(a, b) = a * b + a / b - a % b", "20, 6"},
	{"e2eCmp", "m", "def m(a, b) = a < b == (a >= b)", "3, 5"},
	{"e2eArray", "m", "def m(a, b, c) = [a, b, c]", "1, 2, 3"},
	{"e2eNestArray", "m", "def m(a) = [a, [a, a]]", "5"},
	{"e2eRange", "m", "def m(a) = (1..a)", "5"},
	{"e2eRangeExcl", "m", "def m(a) = (1...a)", "5"},
	{"e2eHash", "m", "def m(a, b) = {x: a, y: b}", "1, 2"},
	{"e2eSplat", "m", "def m(a, b) = [a, *[b, b]]", "1, 2"},
	{"e2eIvar", "m", "def m(a)\n  @x = a\n  @x + 1\nend", "41"},
	{"e2eFib", "fib", "def fib(n) = n < 2 ? n : fib(n - 1) + fib(n - 2)", "10"},
}

func main() {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/aotgen; DO NOT EDIT.\n")
	b.WriteString("package vm\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/go-embedded-ruby/ruby/internal/bytecode\"\n")
	b.WriteString("\t\"github.com/go-embedded-ruby/ruby/internal/object\"\n")
	b.WriteString(")\n\n")

	var slice strings.Builder
	slice.WriteString("// aotE2ECases pairs each compiled method with the reference MRI output\n")
	slice.WriteString("// for the same program, baked at generation time. See aot_e2e_test.go.\n")
	slice.WriteString("var aotE2ECases = []struct {\n")
	slice.WriteString("\tname string\n")
	slice.WriteString("\tfn   func(*VM) object.Value\n")
	slice.WriteString("\truby string // the program whose MRI output is `want`\n")
	slice.WriteString("\twant string // reference MRI stdout (trimmed)\n")
	slice.WriteString("}{\n")

	for _, c := range cases {
		prog, err := parser.Parse(c.def)
		if err != nil {
			fail("parse %s: %v", c.goName, err)
		}
		iseq, err := compiler.Compile(prog)
		if err != nil {
			fail("compile %s: %v", c.goName, err)
		}
		src, ok := aot.Compile(iseq.Children[0], c.goName, c.rubyName)
		if !ok {
			fail("Compile(%s) bailed — cannot emit", c.goName)
		}
		b.WriteString(src)
		b.WriteString("\n")

		var argExprs []string
		for _, a := range strings.Split(c.args, ",") {
			argExprs = append(argExprs, "object.Integer("+strings.TrimSpace(a)+")")
		}
		ruby := c.def + "\np " + c.rubyName + "(" + c.args + ")\n"
		want := mriOutput(ruby)
		fmt.Fprintf(&slice, "\t{%q, func(vm *VM) object.Value { return vm.%s(vm.main, []object.Value{%s}, nil) }, %q, %q},\n",
			c.goName, c.goName, strings.Join(argExprs, ", "), ruby, want)
	}
	slice.WriteString("}\n")
	b.WriteString(slice.String())

	if err := os.WriteFile("aot_e2e_gen_test.go", []byte(b.String()), 0o644); err != nil {
		fail("write: %v", err)
	}
}

func fail(f string, a ...any) {
	fmt.Fprintf(os.Stderr, f+"\n", a...)
	os.Exit(1)
}
