package vm

//go:generate go run ../../cmd/aotgen

import (
	"io"
	"testing"
)

// TestAOTEndToEnd runs each AOT-compiled method (generated by cmd/aotgen, real
// *VM methods lowered from bytecode) and asserts its result Inspects identically
// to the reference MRI output baked into the case at generation time. This
// proves the generated Go — across every Stage-2 opcode — behaves exactly like
// the reference interpreter, deterministically and with no ruby dependency in CI.
func TestAOTEndToEnd(t *testing.T) {
	for _, c := range aotE2ECases {
		t.Run(c.name, func(t *testing.T) {
			got := c.fn(New(io.Discard)).Inspect()
			if got != c.want {
				t.Errorf("AOT result diverges from reference MRI\n ruby: %q\n  AOT: %q\n  MRI: %q",
					c.ruby, got, c.want)
			}
		})
	}
}
