// Code generated by cmd/aotgen; DO NOT EDIT.
package vm

import (
	"github.com/go-embedded-ruby/ruby/internal/bytecode"
	"github.com/go-embedded-ruby/ruby/internal/object"
)

func (vm *VM) e2eArith_l1(self object.Value, args []object.Value, block *Proc) object.Value {
	var l0, l1 object.Value
	l0 = args[0]
	l1 = args[1]
	_ = l0
	_ = l1
	_ = self
	_ = args
	_ = block
	var s0, s1, s2 object.Value
	s0 = l0
	s1 = l1
	s0 = vm.binaryOp(bytecode.OpMul, s0, s1)
	s1 = l0
	s2 = l1
	s1 = vm.binaryOp(bytecode.OpDiv, s1, s2)
	s0 = vm.binaryOp(bytecode.OpAdd, s0, s1)
	s1 = l0
	s2 = l1
	s1 = vm.binaryOp(bytecode.OpMod, s1, s2)
	s0 = vm.binaryOp(bytecode.OpSub, s0, s1)
	return s0
}

func (vm *VM) e2eArith_k(l0, l1 int64) int64 {
	_ = l0
	_ = l1
	var k0, k1, k2 int64
	k0 = l0
	k1 = l1
	k0 = aotMul(k0, k1)
	k1 = l0
	k2 = l1
	k1 = aotDiv(k1, k2)
	k0 = aotAdd(k0, k1)
	k1 = l0
	k2 = l1
	k1 = aotMod(k1, k2)
	k0 = aotSub(k0, k1)
	return k0
}

func (vm *VM) e2eArith(self object.Value, args []object.Value, block *Proc) (res object.Value) {
	i0, ok0 := args[0].(object.Integer)
	if !ok0 {
		return vm.e2eArith_l1(self, args, block)
	}
	i1, ok1 := args[1].(object.Integer)
	if !ok1 {
		return vm.e2eArith_l1(self, args, block)
	}
	defer func() {
		if r := recover(); r != nil {
			if _, d := r.(aotDeopt); d {
				res = vm.e2eArith_l1(self, args, block)
				return
			}
			panic(r)
		}
	}()
	_ = self
	_ = args
	_ = block
	return object.Integer(vm.e2eArith_k(int64(i0), int64(i1)))
}

func (vm *VM) e2eCmp(self object.Value, args []object.Value, block *Proc) object.Value {
	var l0, l1 object.Value
	l0 = args[0]
	l1 = args[1]
	_ = l0
	_ = l1
	_ = self
	_ = args
	_ = block
	var s0, s1, s2 object.Value
	s0 = l0
	s1 = l1
	s0 = vm.binaryOp(bytecode.OpLt, s0, s1)
	s1 = l0
	s2 = l1
	s1 = vm.binaryOp(bytecode.OpGe, s1, s2)
	s0 = vm.binaryOp(bytecode.OpEq, s0, s1)
	return s0
}

func (vm *VM) e2eArray(self object.Value, args []object.Value, block *Proc) object.Value {
	var l0, l1, l2 object.Value
	l0 = args[0]
	l1 = args[1]
	l2 = args[2]
	_ = l0
	_ = l1
	_ = l2
	_ = self
	_ = args
	_ = block
	var s0, s1, s2 object.Value
	s0 = l0
	s1 = l1
	s2 = l2
	s0 = &object.Array{Elems: []object.Value{s0, s1, s2}}
	return s0
}

func (vm *VM) e2eNestArray(self object.Value, args []object.Value, block *Proc) object.Value {
	var l0 object.Value
	l0 = args[0]
	_ = l0
	_ = self
	_ = args
	_ = block
	var s0, s1, s2 object.Value
	s0 = l0
	s1 = l0
	s2 = l0
	s1 = &object.Array{Elems: []object.Value{s1, s2}}
	s0 = &object.Array{Elems: []object.Value{s0, s1}}
	return s0
}

func (vm *VM) e2eRange(self object.Value, args []object.Value, block *Proc) object.Value {
	var l0 object.Value
	l0 = args[0]
	_ = l0
	_ = self
	_ = args
	_ = block
	var s0, s1 object.Value
	s0 = object.Integer(1)
	s1 = l0
	s0 = &object.Range{Lo: s0, Hi: s1, Exclusive: false}
	return s0
}

func (vm *VM) e2eRangeExcl(self object.Value, args []object.Value, block *Proc) object.Value {
	var l0 object.Value
	l0 = args[0]
	_ = l0
	_ = self
	_ = args
	_ = block
	var s0, s1 object.Value
	s0 = object.Integer(1)
	s1 = l0
	s0 = &object.Range{Lo: s0, Hi: s1, Exclusive: true}
	return s0
}

func (vm *VM) e2eHash(self object.Value, args []object.Value, block *Proc) object.Value {
	var l0, l1 object.Value
	l0 = args[0]
	l1 = args[1]
	_ = l0
	_ = l1
	_ = self
	_ = args
	_ = block
	var s0, s1, s2, s3 object.Value
	s0 = object.Symbol("x")
	s1 = l0
	s2 = object.Symbol("y")
	s3 = l1
	{
		h := object.NewHash()
		h.Set(s0, s1)
		h.Set(s2, s3)
		s0 = h
	}
	return s0
}

func (vm *VM) e2eSplat(self object.Value, args []object.Value, block *Proc) object.Value {
	var l0, l1 object.Value
	l0 = args[0]
	l1 = args[1]
	_ = l0
	_ = l1
	_ = self
	_ = args
	_ = block
	var s0, s1, s2 object.Value
	s0 = &object.Array{Elems: []object.Value{}}
	s1 = l0
	s1 = &object.Array{Elems: []object.Value{s1}}
	s0 = aotConcat(s0, s1)
	s1 = l1
	s2 = l1
	s1 = &object.Array{Elems: []object.Value{s1, s2}}
	s1 = aotSplat(s1)
	s0 = aotConcat(s0, s1)
	return s0
}

func (vm *VM) e2eIvar(self object.Value, args []object.Value, block *Proc) object.Value {
	var l0 object.Value
	l0 = args[0]
	_ = l0
	_ = self
	_ = args
	_ = block
	var s0, s1 object.Value
	s0 = l0
	setIvar(self, "@x", s0)
	s0 = getIvar(self, "@x")
	s1 = object.Integer(1)
	s0 = vm.binaryOp(bytecode.OpAdd, s0, s1)
	return s0
}

func (vm *VM) e2eFib_l1(self object.Value, args []object.Value, block *Proc) object.Value {
	var l0 object.Value
	l0 = args[0]
	_ = l0
	_ = self
	_ = args
	_ = block
	var s0, s1, s2, s3 object.Value
	s0 = l0
	s1 = object.Integer(2)
	s0 = vm.binaryOp(bytecode.OpLt, s0, s1)
	if !s0.Truthy() { goto L6 }
	s0 = l0
	goto L17
L6:
	s0 = self
	s1 = l0
	s2 = object.Integer(1)
	s1 = vm.binaryOp(bytecode.OpSub, s1, s2)
	s0 = vm.e2eFib_l1(self, []object.Value{s1}, nil)
	s1 = self
	s2 = l0
	s3 = object.Integer(2)
	s2 = vm.binaryOp(bytecode.OpSub, s2, s3)
	s1 = vm.e2eFib_l1(self, []object.Value{s2}, nil)
	s0 = vm.binaryOp(bytecode.OpAdd, s0, s1)
L17:
	return s0
}

func (vm *VM) e2eFib_k(l0 int64) int64 {
	_ = l0
	var k0, k1, k2, k3 int64
	k0 = l0
	k1 = 2
	if !(k0 < k1) { goto L6 }
	k0 = l0
	goto L17
L6:
	k1 = l0
	k2 = 1
	k1 = aotSub(k1, k2)
	k0 = vm.e2eFib_k(k1)
	k2 = l0
	k3 = 2
	k2 = aotSub(k2, k3)
	k1 = vm.e2eFib_k(k2)
	k0 = aotAdd(k0, k1)
L17:
	return k0
}

func (vm *VM) e2eFib(self object.Value, args []object.Value, block *Proc) (res object.Value) {
	i0, ok0 := args[0].(object.Integer)
	if !ok0 {
		return vm.e2eFib_l1(self, args, block)
	}
	defer func() {
		if r := recover(); r != nil {
			if _, d := r.(aotDeopt); d {
				res = vm.e2eFib_l1(self, args, block)
				return
			}
			panic(r)
		}
	}()
	_ = self
	_ = args
	_ = block
	return object.Integer(vm.e2eFib_k(int64(i0)))
}

func (vm *VM) e2eDiv_l1(self object.Value, args []object.Value, block *Proc) object.Value {
	var l0, l1 object.Value
	l0 = args[0]
	l1 = args[1]
	_ = l0
	_ = l1
	_ = self
	_ = args
	_ = block
	var s0, s1 object.Value
	s0 = l0
	s1 = l1
	s0 = vm.binaryOp(bytecode.OpDiv, s0, s1)
	return s0
}

func (vm *VM) e2eDiv_k(l0, l1 int64) int64 {
	_ = l0
	_ = l1
	var k0, k1 int64
	k0 = l0
	k1 = l1
	k0 = aotDiv(k0, k1)
	return k0
}

func (vm *VM) e2eDiv(self object.Value, args []object.Value, block *Proc) (res object.Value) {
	i0, ok0 := args[0].(object.Integer)
	if !ok0 {
		return vm.e2eDiv_l1(self, args, block)
	}
	i1, ok1 := args[1].(object.Integer)
	if !ok1 {
		return vm.e2eDiv_l1(self, args, block)
	}
	defer func() {
		if r := recover(); r != nil {
			if _, d := r.(aotDeopt); d {
				res = vm.e2eDiv_l1(self, args, block)
				return
			}
			panic(r)
		}
	}()
	_ = self
	_ = args
	_ = block
	return object.Integer(vm.e2eDiv_k(int64(i0), int64(i1)))
}

func (vm *VM) e2eMulOverflow_l1(self object.Value, args []object.Value, block *Proc) object.Value {
	var l0, l1 object.Value
	l0 = args[0]
	l1 = args[1]
	_ = l0
	_ = l1
	_ = self
	_ = args
	_ = block
	var s0, s1 object.Value
	s0 = l0
	s1 = l1
	s0 = vm.binaryOp(bytecode.OpMul, s0, s1)
	return s0
}

func (vm *VM) e2eMulOverflow_k(l0, l1 int64) int64 {
	_ = l0
	_ = l1
	var k0, k1 int64
	k0 = l0
	k1 = l1
	k0 = aotMul(k0, k1)
	return k0
}

func (vm *VM) e2eMulOverflow(self object.Value, args []object.Value, block *Proc) (res object.Value) {
	i0, ok0 := args[0].(object.Integer)
	if !ok0 {
		return vm.e2eMulOverflow_l1(self, args, block)
	}
	i1, ok1 := args[1].(object.Integer)
	if !ok1 {
		return vm.e2eMulOverflow_l1(self, args, block)
	}
	defer func() {
		if r := recover(); r != nil {
			if _, d := r.(aotDeopt); d {
				res = vm.e2eMulOverflow_l1(self, args, block)
				return
			}
			panic(r)
		}
	}()
	_ = self
	_ = args
	_ = block
	return object.Integer(vm.e2eMulOverflow_k(int64(i0), int64(i1)))
}

func (vm *VM) e2eFloatDeopt_l1(self object.Value, args []object.Value, block *Proc) object.Value {
	var l0 object.Value
	l0 = args[0]
	_ = l0
	_ = self
	_ = args
	_ = block
	var s0, s1 object.Value
	s0 = l0
	s1 = object.Integer(1)
	s0 = vm.binaryOp(bytecode.OpAdd, s0, s1)
	return s0
}

func (vm *VM) e2eFloatDeopt_k(l0 int64) int64 {
	_ = l0
	var k0, k1 int64
	k0 = l0
	k1 = 1
	k0 = aotAdd(k0, k1)
	return k0
}

func (vm *VM) e2eFloatDeopt(self object.Value, args []object.Value, block *Proc) (res object.Value) {
	i0, ok0 := args[0].(object.Integer)
	if !ok0 {
		return vm.e2eFloatDeopt_l1(self, args, block)
	}
	defer func() {
		if r := recover(); r != nil {
			if _, d := r.(aotDeopt); d {
				res = vm.e2eFloatDeopt_l1(self, args, block)
				return
			}
			panic(r)
		}
	}()
	_ = self
	_ = args
	_ = block
	return object.Integer(vm.e2eFloatDeopt_k(int64(i0)))
}

func (vm *VM) e2eFact_l1(self object.Value, args []object.Value, block *Proc) object.Value {
	var l0, l1 object.Value
	l0 = args[0]
	_ = l0
	_ = l1
	_ = self
	_ = args
	_ = block
	var s0, s1 object.Value
	s0 = object.Integer(1)
	l1 = s0
L3:
	s0 = l0
	s1 = object.Integer(1)
	s0 = vm.binaryOp(bytecode.OpGt, s0, s1)
	if !s0.Truthy() { goto L18 }
	s0 = l1
	s1 = l0
	s0 = vm.binaryOp(bytecode.OpMul, s0, s1)
	l1 = s0
	s0 = l0
	s1 = object.Integer(1)
	s0 = vm.binaryOp(bytecode.OpSub, s0, s1)
	l0 = s0
	goto L3
L18:
	s0 = object.NilV
	s0 = l1
	return s0
}

func (vm *VM) e2eFact_k(l0 int64) int64 {
	var l1 int64
	_ = l0
	_ = l1
	var k0, k1 int64
	k0 = 1
	l1 = k0
L3:
	k0 = l0
	k1 = 1
	if !(k0 > k1) { goto L18 }
	k0 = l1
	k1 = l0
	k0 = aotMul(k0, k1)
	l1 = k0
	k0 = l0
	k1 = 1
	k0 = aotSub(k0, k1)
	l0 = k0
	goto L3
L18:
	k0 = 0
	k0 = l1
	return k0
}

func (vm *VM) e2eFact(self object.Value, args []object.Value, block *Proc) (res object.Value) {
	i0, ok0 := args[0].(object.Integer)
	if !ok0 {
		return vm.e2eFact_l1(self, args, block)
	}
	defer func() {
		if r := recover(); r != nil {
			if _, d := r.(aotDeopt); d {
				res = vm.e2eFact_l1(self, args, block)
				return
			}
			panic(r)
		}
	}()
	_ = self
	_ = args
	_ = block
	return object.Integer(vm.e2eFact_k(int64(i0)))
}

func (vm *VM) e2eFactBig_l1(self object.Value, args []object.Value, block *Proc) object.Value {
	var l0, l1 object.Value
	l0 = args[0]
	_ = l0
	_ = l1
	_ = self
	_ = args
	_ = block
	var s0, s1 object.Value
	s0 = object.Integer(1)
	l1 = s0
L3:
	s0 = l0
	s1 = object.Integer(1)
	s0 = vm.binaryOp(bytecode.OpGt, s0, s1)
	if !s0.Truthy() { goto L18 }
	s0 = l1
	s1 = l0
	s0 = vm.binaryOp(bytecode.OpMul, s0, s1)
	l1 = s0
	s0 = l0
	s1 = object.Integer(1)
	s0 = vm.binaryOp(bytecode.OpSub, s0, s1)
	l0 = s0
	goto L3
L18:
	s0 = object.NilV
	s0 = l1
	return s0
}

func (vm *VM) e2eFactBig_k(l0 int64) int64 {
	var l1 int64
	_ = l0
	_ = l1
	var k0, k1 int64
	k0 = 1
	l1 = k0
L3:
	k0 = l0
	k1 = 1
	if !(k0 > k1) { goto L18 }
	k0 = l1
	k1 = l0
	k0 = aotMul(k0, k1)
	l1 = k0
	k0 = l0
	k1 = 1
	k0 = aotSub(k0, k1)
	l0 = k0
	goto L3
L18:
	k0 = 0
	k0 = l1
	return k0
}

func (vm *VM) e2eFactBig(self object.Value, args []object.Value, block *Proc) (res object.Value) {
	i0, ok0 := args[0].(object.Integer)
	if !ok0 {
		return vm.e2eFactBig_l1(self, args, block)
	}
	defer func() {
		if r := recover(); r != nil {
			if _, d := r.(aotDeopt); d {
				res = vm.e2eFactBig_l1(self, args, block)
				return
			}
			panic(r)
		}
	}()
	_ = self
	_ = args
	_ = block
	return object.Integer(vm.e2eFactBig_k(int64(i0)))
}

// aotE2ECases pairs each compiled method with the reference MRI output
// for the same program, baked at generation time. See aot_e2e_test.go.
var aotE2ECases = []struct {
	name string
	fn   func(*VM) object.Value
	ruby string // the program whose MRI output is `want`
	want string // reference MRI stdout (trimmed)
}{
	{"e2eArith", func(vm *VM) object.Value { return vm.e2eArith(vm.main, []object.Value{object.Integer(20), object.Integer(6)}, nil) }, "def m(a, b) = a * b + a / b - a % b\np m(20, 6)\n", "121"},
	{"e2eCmp", func(vm *VM) object.Value { return vm.e2eCmp(vm.main, []object.Value{object.Integer(3), object.Integer(5)}, nil) }, "def m(a, b) = a < b == (a >= b)\np m(3, 5)\n", "false"},
	{"e2eArray", func(vm *VM) object.Value { return vm.e2eArray(vm.main, []object.Value{object.Integer(1), object.Integer(2), object.Integer(3)}, nil) }, "def m(a, b, c) = [a, b, c]\np m(1, 2, 3)\n", "[1, 2, 3]"},
	{"e2eNestArray", func(vm *VM) object.Value { return vm.e2eNestArray(vm.main, []object.Value{object.Integer(5)}, nil) }, "def m(a) = [a, [a, a]]\np m(5)\n", "[5, [5, 5]]"},
	{"e2eRange", func(vm *VM) object.Value { return vm.e2eRange(vm.main, []object.Value{object.Integer(5)}, nil) }, "def m(a) = (1..a)\np m(5)\n", "1..5"},
	{"e2eRangeExcl", func(vm *VM) object.Value { return vm.e2eRangeExcl(vm.main, []object.Value{object.Integer(5)}, nil) }, "def m(a) = (1...a)\np m(5)\n", "1...5"},
	{"e2eHash", func(vm *VM) object.Value { return vm.e2eHash(vm.main, []object.Value{object.Integer(1), object.Integer(2)}, nil) }, "def m(a, b) = {x: a, y: b}\np m(1, 2)\n", "{x: 1, y: 2}"},
	{"e2eSplat", func(vm *VM) object.Value { return vm.e2eSplat(vm.main, []object.Value{object.Integer(1), object.Integer(2)}, nil) }, "def m(a, b) = [a, *[b, b]]\np m(1, 2)\n", "[1, 2, 2]"},
	{"e2eIvar", func(vm *VM) object.Value { return vm.e2eIvar(vm.main, []object.Value{object.Integer(41)}, nil) }, "def m(a)\n  @x = a\n  @x + 1\nend\np m(41)\n", "42"},
	{"e2eFib", func(vm *VM) object.Value { return vm.e2eFib(vm.main, []object.Value{object.Integer(10)}, nil) }, "def fib(n) = n < 2 ? n : fib(n - 1) + fib(n - 2)\np fib(10)\n", "55"},
	{"e2eDiv", func(vm *VM) object.Value { return vm.e2eDiv(vm.main, []object.Value{object.Integer(17), object.Integer(5)}, nil) }, "def m(a, b) = a / b\np m(17, 5)\n", "3"},
	{"e2eMulOverflow", func(vm *VM) object.Value { return vm.e2eMulOverflow(vm.main, []object.Value{object.Integer(1000000000000), object.Integer(1000000000000)}, nil) }, "def m(a, b) = a * b\np m(1000000000000, 1000000000000)\n", "1000000000000000000000000"},
	{"e2eFloatDeopt", func(vm *VM) object.Value { return vm.e2eFloatDeopt(vm.main, []object.Value{object.Float(1.5)}, nil) }, "def m(a) = a + 1\np m(1.5)\n", "2.5"},
	{"e2eFact", func(vm *VM) object.Value { return vm.e2eFact(vm.main, []object.Value{object.Integer(10)}, nil) }, "def m(n)\n  r = 1\n  while n > 1\n    r = r * n\n    n = n - 1\n  end\n  r\nend\np m(10)\n", "3628800"},
	{"e2eFactBig", func(vm *VM) object.Value { return vm.e2eFactBig(vm.main, []object.Value{object.Integer(25)}, nil) }, "def m(n)\n  r = 1\n  while n > 1\n    r = r * n\n    n = n - 1\n  end\n  r\nend\np m(25)\n", "15511210043330985984000000"},
}
