package vm

//go:generate go run ../../cmd/aotgen

import (
	"io"
	"os"
	"os/exec"
	"strings"
	"testing"
)

// mri is the reference interpreter; tests that diff against it skip when absent.
func mri(t *testing.T) string {
	t.Helper()
	for _, p := range []string{"/opt/homebrew/opt/ruby/bin/ruby", "ruby"} {
		if path, err := exec.LookPath(p); err == nil {
			return path
		}
	}
	t.Skip("MRI ruby not found; skipping differential test")
	return ""
}

// TestAOTEndToEnd runs each AOT-compiled method (generated by aotgen, real *VM
// methods lowered from bytecode) and asserts its result Inspects identically to
// what MRI prints for the same program. This proves the generated Go — across
// every Stage-2 opcode — behaves exactly like the reference interpreter.
func TestAOTEndToEnd(t *testing.T) {
	ruby := mri(t)
	for _, c := range aotE2ECases {
		t.Run(c.name, func(t *testing.T) {
			vm := New(io.Discard)
			got := c.fn(vm).Inspect()

			cmd := exec.Command(ruby, "-e", c.ruby)
			cmd.Env = append(os.Environ(), "RUBYOPT=") // ignore any ambient YJIT/opts
			out, err := cmd.Output()
			if err != nil {
				t.Fatalf("MRI failed for %s: %v", c.name, err)
			}
			want := strings.TrimRight(string(out), "\n")

			if got != want {
				t.Errorf("AOT result diverges from MRI\n ruby: %q\n  AOT: %q\n  MRI: %q",
					c.ruby, got, want)
			}
		})
	}
}
