package vm

import (
	"io"
	"testing"

	"github.com/go-embedded-ruby/ruby/internal/object"
)

// TestAOTDivByZeroDeopt drives the level-3 divide kernel (e2eDiv, generated by
// aotgen) into its deopt edge: a zero divisor makes aotDiv panic aotDeopt, which
// the wrapper recovers and re-runs through the level-1 body — which raises
// ZeroDivisionError exactly as the interpreter (and MRI) would.
func TestAOTDivByZeroDeopt(t *testing.T) {
	vm := New(io.Discard)
	wantRaise(t, "ZeroDivisionError", func() {
		vm.e2eDiv(vm.main, []object.Value{object.Integer(10), object.Integer(0)}, nil)
	})
}

// BenchmarkAOTGeneratedL3Fib measures the *generated* level-3 fib (e2eFib) — the
// real codegen output, not the hand-written prototype — confirming the compiler
// reaches the unboxed-kernel speed that beats YJIT.
func BenchmarkAOTGeneratedL3Fib(b *testing.B) {
	vm := New(io.Discard)
	arg := []object.Value{object.Integer(30)}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_ = vm.e2eFib(vm.main, arg, nil)
	}
}
