package vm

// Code generated from the Ruby 3.4/4.0 Encoding registry. DO NOT EDIT.
// Regenerate with scripts/gen_encoding_table.rb against a reference ruby.

// encInfo is one registered (non-alias) encoding: its canonical name, the
// aliases pointing at it (in MRI #names order, canonical first is implied), and
// its dummy / ASCII-compatible flags.
type encInfo struct {
	name        string
	aliases     []string
	dummy       bool
	asciiCompat bool
}

// encTable lists every registered encoding in Encoding.list order.
var encTable = []encInfo{
	{name: "ASCII-8BIT", aliases: []string{"BINARY"}, dummy: false, asciiCompat: true},
	{name: "UTF-8", aliases: []string{"CP65001", "locale", "external", "filesystem"}, dummy: false, asciiCompat: true},
	{name: "US-ASCII", aliases: []string{"ASCII", "ANSI_X3.4-1968", "646"}, dummy: false, asciiCompat: true},
	{name: "UTF-16BE", aliases: []string{"UCS-2BE"}, dummy: false, asciiCompat: false},
	{name: "UTF-16LE", aliases: []string{}, dummy: false, asciiCompat: false},
	{name: "UTF-32BE", aliases: []string{"UCS-4BE"}, dummy: false, asciiCompat: false},
	{name: "UTF-32LE", aliases: []string{"UCS-4LE"}, dummy: false, asciiCompat: false},
	{name: "UTF-16", aliases: []string{}, dummy: true, asciiCompat: false},
	{name: "UTF-32", aliases: []string{}, dummy: true, asciiCompat: false},
	{name: "UTF8-MAC", aliases: []string{"UTF-8-MAC", "UTF-8-HFS"}, dummy: false, asciiCompat: true},
	{name: "EUC-JP", aliases: []string{"eucJP"}, dummy: false, asciiCompat: true},
	{name: "Windows-31J", aliases: []string{"CP932", "csWindows31J", "SJIS", "PCK"}, dummy: false, asciiCompat: true},
	{name: "Big5", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "Big5-HKSCS", aliases: []string{"Big5-HKSCS:2008"}, dummy: false, asciiCompat: true},
	{name: "Big5-UAO", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "CESU-8", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "CP949", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "Emacs-Mule", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "EUC-KR", aliases: []string{"eucKR"}, dummy: false, asciiCompat: true},
	{name: "EUC-TW", aliases: []string{"eucTW"}, dummy: false, asciiCompat: true},
	{name: "GB18030", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "GBK", aliases: []string{"CP936"}, dummy: false, asciiCompat: true},
	{name: "ISO-8859-1", aliases: []string{"ISO8859-1"}, dummy: false, asciiCompat: true},
	{name: "ISO-8859-2", aliases: []string{"ISO8859-2"}, dummy: false, asciiCompat: true},
	{name: "ISO-8859-3", aliases: []string{"ISO8859-3"}, dummy: false, asciiCompat: true},
	{name: "ISO-8859-4", aliases: []string{"ISO8859-4"}, dummy: false, asciiCompat: true},
	{name: "ISO-8859-5", aliases: []string{"ISO8859-5"}, dummy: false, asciiCompat: true},
	{name: "ISO-8859-6", aliases: []string{"ISO8859-6"}, dummy: false, asciiCompat: true},
	{name: "ISO-8859-7", aliases: []string{"ISO8859-7"}, dummy: false, asciiCompat: true},
	{name: "ISO-8859-8", aliases: []string{"ISO8859-8"}, dummy: false, asciiCompat: true},
	{name: "ISO-8859-9", aliases: []string{"ISO8859-9"}, dummy: false, asciiCompat: true},
	{name: "ISO-8859-10", aliases: []string{"ISO8859-10"}, dummy: false, asciiCompat: true},
	{name: "ISO-8859-11", aliases: []string{"ISO8859-11"}, dummy: false, asciiCompat: true},
	{name: "ISO-8859-13", aliases: []string{"ISO8859-13"}, dummy: false, asciiCompat: true},
	{name: "ISO-8859-14", aliases: []string{"ISO8859-14"}, dummy: false, asciiCompat: true},
	{name: "ISO-8859-15", aliases: []string{"ISO8859-15"}, dummy: false, asciiCompat: true},
	{name: "ISO-8859-16", aliases: []string{"ISO8859-16"}, dummy: false, asciiCompat: true},
	{name: "KOI8-R", aliases: []string{"CP878"}, dummy: false, asciiCompat: true},
	{name: "KOI8-U", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "Shift_JIS", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "Windows-1250", aliases: []string{"CP1250"}, dummy: false, asciiCompat: true},
	{name: "Windows-1251", aliases: []string{"CP1251"}, dummy: false, asciiCompat: true},
	{name: "Windows-1252", aliases: []string{"CP1252"}, dummy: false, asciiCompat: true},
	{name: "Windows-1253", aliases: []string{"CP1253"}, dummy: false, asciiCompat: true},
	{name: "Windows-1254", aliases: []string{"CP1254"}, dummy: false, asciiCompat: true},
	{name: "Windows-1257", aliases: []string{"CP1257"}, dummy: false, asciiCompat: true},
	{name: "IBM437", aliases: []string{"CP437"}, dummy: false, asciiCompat: true},
	{name: "IBM720", aliases: []string{"CP720"}, dummy: false, asciiCompat: true},
	{name: "IBM737", aliases: []string{"CP737"}, dummy: false, asciiCompat: true},
	{name: "IBM775", aliases: []string{"CP775"}, dummy: false, asciiCompat: true},
	{name: "CP850", aliases: []string{"IBM850"}, dummy: false, asciiCompat: true},
	{name: "IBM852", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "CP852", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "IBM855", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "CP855", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "IBM857", aliases: []string{"CP857"}, dummy: false, asciiCompat: true},
	{name: "IBM860", aliases: []string{"CP860"}, dummy: false, asciiCompat: true},
	{name: "IBM861", aliases: []string{"CP861"}, dummy: false, asciiCompat: true},
	{name: "IBM862", aliases: []string{"CP862"}, dummy: false, asciiCompat: true},
	{name: "IBM863", aliases: []string{"CP863"}, dummy: false, asciiCompat: true},
	{name: "IBM864", aliases: []string{"CP864"}, dummy: false, asciiCompat: true},
	{name: "IBM865", aliases: []string{"CP865"}, dummy: false, asciiCompat: true},
	{name: "IBM866", aliases: []string{"CP866"}, dummy: false, asciiCompat: true},
	{name: "IBM869", aliases: []string{"CP869"}, dummy: false, asciiCompat: true},
	{name: "Windows-1258", aliases: []string{"CP1258"}, dummy: false, asciiCompat: true},
	{name: "GB1988", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "macCentEuro", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "macCroatian", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "macCyrillic", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "macGreek", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "macIceland", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "macRoman", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "macRomania", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "macThai", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "macTurkish", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "macUkraine", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "CP950", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "CP951", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "IBM037", aliases: []string{"ebcdic-cp-us"}, dummy: true, asciiCompat: false},
	{name: "stateless-ISO-2022-JP", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "eucJP-ms", aliases: []string{"euc-jp-ms"}, dummy: false, asciiCompat: true},
	{name: "CP51932", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "EUC-JIS-2004", aliases: []string{"EUC-JISX0213"}, dummy: false, asciiCompat: true},
	{name: "GB2312", aliases: []string{"EUC-CN", "eucCN"}, dummy: false, asciiCompat: true},
	{name: "GB12345", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "ISO-2022-JP", aliases: []string{"ISO2022-JP"}, dummy: true, asciiCompat: false},
	{name: "ISO-2022-JP-2", aliases: []string{"ISO2022-JP2"}, dummy: true, asciiCompat: false},
	{name: "CP50220", aliases: []string{}, dummy: true, asciiCompat: false},
	{name: "CP50221", aliases: []string{}, dummy: true, asciiCompat: false},
	{name: "Windows-1256", aliases: []string{"CP1256"}, dummy: false, asciiCompat: true},
	{name: "Windows-1255", aliases: []string{"CP1255"}, dummy: false, asciiCompat: true},
	{name: "TIS-620", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "Windows-874", aliases: []string{"CP874"}, dummy: false, asciiCompat: true},
	{name: "MacJapanese", aliases: []string{"MacJapan"}, dummy: false, asciiCompat: true},
	{name: "UTF-7", aliases: []string{"CP65000"}, dummy: true, asciiCompat: false},
	{name: "UTF8-DoCoMo", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "SJIS-DoCoMo", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "UTF8-KDDI", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "SJIS-KDDI", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "ISO-2022-JP-KDDI", aliases: []string{}, dummy: true, asciiCompat: false},
	{name: "stateless-ISO-2022-JP-KDDI", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "UTF8-SoftBank", aliases: []string{}, dummy: false, asciiCompat: true},
	{name: "SJIS-SoftBank", aliases: []string{}, dummy: false, asciiCompat: true},
}

// encConstNames maps every Encoding:: constant to its canonical encoding name.
var encConstNames = map[string]string{
	"ANSI_X3_4_1968":             "US-ASCII",
	"ASCII":                      "US-ASCII",
	"ASCII_8BIT":                 "ASCII-8BIT",
	"BIG5":                       "Big5",
	"BIG5_HKSCS":                 "Big5-HKSCS",
	"BIG5_HKSCS_2008":            "Big5-HKSCS",
	"BIG5_UAO":                   "Big5-UAO",
	"BINARY":                     "ASCII-8BIT",
	"Big5":                       "Big5",
	"Big5_HKSCS":                 "Big5-HKSCS",
	"Big5_HKSCS_2008":            "Big5-HKSCS",
	"Big5_UAO":                   "Big5-UAO",
	"CESU_8":                     "CESU-8",
	"CP1250":                     "Windows-1250",
	"CP1251":                     "Windows-1251",
	"CP1252":                     "Windows-1252",
	"CP1253":                     "Windows-1253",
	"CP1254":                     "Windows-1254",
	"CP1255":                     "Windows-1255",
	"CP1256":                     "Windows-1256",
	"CP1257":                     "Windows-1257",
	"CP1258":                     "Windows-1258",
	"CP437":                      "IBM437",
	"CP50220":                    "CP50220",
	"CP50221":                    "CP50221",
	"CP51932":                    "CP51932",
	"CP65000":                    "UTF-7",
	"CP65001":                    "UTF-8",
	"CP720":                      "IBM720",
	"CP737":                      "IBM737",
	"CP775":                      "IBM775",
	"CP850":                      "CP850",
	"CP852":                      "CP852",
	"CP855":                      "CP855",
	"CP857":                      "IBM857",
	"CP860":                      "IBM860",
	"CP861":                      "IBM861",
	"CP862":                      "IBM862",
	"CP863":                      "IBM863",
	"CP864":                      "IBM864",
	"CP865":                      "IBM865",
	"CP866":                      "IBM866",
	"CP869":                      "IBM869",
	"CP874":                      "Windows-874",
	"CP878":                      "KOI8-R",
	"CP932":                      "Windows-31J",
	"CP936":                      "GBK",
	"CP949":                      "CP949",
	"CP950":                      "CP950",
	"CP951":                      "CP951",
	"CSWINDOWS31J":               "Windows-31J",
	"CsWindows31J":               "Windows-31J",
	"EBCDIC_CP_US":               "IBM037",
	"EMACS_MULE":                 "Emacs-Mule",
	"EUCCN":                      "GB2312",
	"EUCJP":                      "EUC-JP",
	"EUCJP_MS":                   "eucJP-ms",
	"EUCKR":                      "EUC-KR",
	"EUCTW":                      "EUC-TW",
	"EUC_CN":                     "GB2312",
	"EUC_JISX0213":               "EUC-JIS-2004",
	"EUC_JIS_2004":               "EUC-JIS-2004",
	"EUC_JP":                     "EUC-JP",
	"EUC_JP_MS":                  "eucJP-ms",
	"EUC_KR":                     "EUC-KR",
	"EUC_TW":                     "EUC-TW",
	"Emacs_Mule":                 "Emacs-Mule",
	"EucCN":                      "GB2312",
	"EucJP":                      "EUC-JP",
	"EucJP_ms":                   "eucJP-ms",
	"EucKR":                      "EUC-KR",
	"EucTW":                      "EUC-TW",
	"GB12345":                    "GB12345",
	"GB18030":                    "GB18030",
	"GB1988":                     "GB1988",
	"GB2312":                     "GB2312",
	"GBK":                        "GBK",
	"IBM037":                     "IBM037",
	"IBM437":                     "IBM437",
	"IBM720":                     "IBM720",
	"IBM737":                     "IBM737",
	"IBM775":                     "IBM775",
	"IBM850":                     "CP850",
	"IBM852":                     "IBM852",
	"IBM855":                     "IBM855",
	"IBM857":                     "IBM857",
	"IBM860":                     "IBM860",
	"IBM861":                     "IBM861",
	"IBM862":                     "IBM862",
	"IBM863":                     "IBM863",
	"IBM864":                     "IBM864",
	"IBM865":                     "IBM865",
	"IBM866":                     "IBM866",
	"IBM869":                     "IBM869",
	"ISO2022_JP":                 "ISO-2022-JP",
	"ISO2022_JP2":                "ISO-2022-JP-2",
	"ISO8859_1":                  "ISO-8859-1",
	"ISO8859_10":                 "ISO-8859-10",
	"ISO8859_11":                 "ISO-8859-11",
	"ISO8859_13":                 "ISO-8859-13",
	"ISO8859_14":                 "ISO-8859-14",
	"ISO8859_15":                 "ISO-8859-15",
	"ISO8859_16":                 "ISO-8859-16",
	"ISO8859_2":                  "ISO-8859-2",
	"ISO8859_3":                  "ISO-8859-3",
	"ISO8859_4":                  "ISO-8859-4",
	"ISO8859_5":                  "ISO-8859-5",
	"ISO8859_6":                  "ISO-8859-6",
	"ISO8859_7":                  "ISO-8859-7",
	"ISO8859_8":                  "ISO-8859-8",
	"ISO8859_9":                  "ISO-8859-9",
	"ISO_2022_JP":                "ISO-2022-JP",
	"ISO_2022_JP_2":              "ISO-2022-JP-2",
	"ISO_2022_JP_KDDI":           "ISO-2022-JP-KDDI",
	"ISO_8859_1":                 "ISO-8859-1",
	"ISO_8859_10":                "ISO-8859-10",
	"ISO_8859_11":                "ISO-8859-11",
	"ISO_8859_13":                "ISO-8859-13",
	"ISO_8859_14":                "ISO-8859-14",
	"ISO_8859_15":                "ISO-8859-15",
	"ISO_8859_16":                "ISO-8859-16",
	"ISO_8859_2":                 "ISO-8859-2",
	"ISO_8859_3":                 "ISO-8859-3",
	"ISO_8859_4":                 "ISO-8859-4",
	"ISO_8859_5":                 "ISO-8859-5",
	"ISO_8859_6":                 "ISO-8859-6",
	"ISO_8859_7":                 "ISO-8859-7",
	"ISO_8859_8":                 "ISO-8859-8",
	"ISO_8859_9":                 "ISO-8859-9",
	"KOI8_R":                     "KOI8-R",
	"KOI8_U":                     "KOI8-U",
	"MACCENTEURO":                "macCentEuro",
	"MACCROATIAN":                "macCroatian",
	"MACCYRILLIC":                "macCyrillic",
	"MACGREEK":                   "macGreek",
	"MACICELAND":                 "macIceland",
	"MACJAPAN":                   "MacJapanese",
	"MACJAPANESE":                "MacJapanese",
	"MACROMAN":                   "macRoman",
	"MACROMANIA":                 "macRomania",
	"MACTHAI":                    "macThai",
	"MACTURKISH":                 "macTurkish",
	"MACUKRAINE":                 "macUkraine",
	"MacCentEuro":                "macCentEuro",
	"MacCroatian":                "macCroatian",
	"MacCyrillic":                "macCyrillic",
	"MacGreek":                   "macGreek",
	"MacIceland":                 "macIceland",
	"MacJapan":                   "MacJapanese",
	"MacJapanese":                "MacJapanese",
	"MacRoman":                   "macRoman",
	"MacRomania":                 "macRomania",
	"MacThai":                    "macThai",
	"MacTurkish":                 "macTurkish",
	"MacUkraine":                 "macUkraine",
	"PCK":                        "Windows-31J",
	"SHIFT_JIS":                  "Shift_JIS",
	"SJIS":                       "Windows-31J",
	"SJIS_DOCOMO":                "SJIS-DoCoMo",
	"SJIS_DoCoMo":                "SJIS-DoCoMo",
	"SJIS_KDDI":                  "SJIS-KDDI",
	"SJIS_SOFTBANK":              "SJIS-SoftBank",
	"SJIS_SoftBank":              "SJIS-SoftBank",
	"STATELESS_ISO_2022_JP":      "stateless-ISO-2022-JP",
	"STATELESS_ISO_2022_JP_KDDI": "stateless-ISO-2022-JP-KDDI",
	"Shift_JIS":                  "Shift_JIS",
	"Stateless_ISO_2022_JP":      "stateless-ISO-2022-JP",
	"Stateless_ISO_2022_JP_KDDI": "stateless-ISO-2022-JP-KDDI",
	"TIS_620":                    "TIS-620",
	"UCS_2BE":                    "UTF-16BE",
	"UCS_4BE":                    "UTF-32BE",
	"UCS_4LE":                    "UTF-32LE",
	"US_ASCII":                   "US-ASCII",
	"UTF8_DOCOMO":                "UTF8-DoCoMo",
	"UTF8_DoCoMo":                "UTF8-DoCoMo",
	"UTF8_KDDI":                  "UTF8-KDDI",
	"UTF8_MAC":                   "UTF8-MAC",
	"UTF8_SOFTBANK":              "UTF8-SoftBank",
	"UTF8_SoftBank":              "UTF8-SoftBank",
	"UTF_16":                     "UTF-16",
	"UTF_16BE":                   "UTF-16BE",
	"UTF_16LE":                   "UTF-16LE",
	"UTF_32":                     "UTF-32",
	"UTF_32BE":                   "UTF-32BE",
	"UTF_32LE":                   "UTF-32LE",
	"UTF_7":                      "UTF-7",
	"UTF_8":                      "UTF-8",
	"UTF_8_HFS":                  "UTF8-MAC",
	"UTF_8_MAC":                  "UTF8-MAC",
	"WINDOWS_1250":               "Windows-1250",
	"WINDOWS_1251":               "Windows-1251",
	"WINDOWS_1252":               "Windows-1252",
	"WINDOWS_1253":               "Windows-1253",
	"WINDOWS_1254":               "Windows-1254",
	"WINDOWS_1255":               "Windows-1255",
	"WINDOWS_1256":               "Windows-1256",
	"WINDOWS_1257":               "Windows-1257",
	"WINDOWS_1258":               "Windows-1258",
	"WINDOWS_31J":                "Windows-31J",
	"WINDOWS_874":                "Windows-874",
	"Windows_1250":               "Windows-1250",
	"Windows_1251":               "Windows-1251",
	"Windows_1252":               "Windows-1252",
	"Windows_1253":               "Windows-1253",
	"Windows_1254":               "Windows-1254",
	"Windows_1255":               "Windows-1255",
	"Windows_1256":               "Windows-1256",
	"Windows_1257":               "Windows-1257",
	"Windows_1258":               "Windows-1258",
	"Windows_31J":                "Windows-31J",
	"Windows_874":                "Windows-874",
}

// encAliasNames maps every alias (as returned by Encoding.aliases) to the
// canonical name it resolves to. Dynamic entries (external/filesystem/locale)
// are pinned to UTF-8, rbgo's default_external.
var encAliasNames = map[string]string{
	"BINARY":          "ASCII-8BIT",
	"CP437":           "IBM437",
	"CP720":           "IBM720",
	"CP737":           "IBM737",
	"CP775":           "IBM775",
	"IBM850":          "CP850",
	"CP857":           "IBM857",
	"CP860":           "IBM860",
	"CP861":           "IBM861",
	"CP862":           "IBM862",
	"CP863":           "IBM863",
	"CP864":           "IBM864",
	"CP865":           "IBM865",
	"CP866":           "IBM866",
	"CP869":           "IBM869",
	"CP1258":          "Windows-1258",
	"Big5-HKSCS:2008": "Big5-HKSCS",
	"ebcdic-cp-us":    "IBM037",
	"eucJP":           "EUC-JP",
	"euc-jp-ms":       "eucJP-ms",
	"EUC-JISX0213":    "EUC-JIS-2004",
	"eucKR":           "EUC-KR",
	"eucTW":           "EUC-TW",
	"EUC-CN":          "GB2312",
	"eucCN":           "GB2312",
	"CP936":           "GBK",
	"ISO2022-JP":      "ISO-2022-JP",
	"ISO2022-JP2":     "ISO-2022-JP-2",
	"ISO8859-1":       "ISO-8859-1",
	"ISO8859-2":       "ISO-8859-2",
	"ISO8859-3":       "ISO-8859-3",
	"ISO8859-4":       "ISO-8859-4",
	"ISO8859-5":       "ISO-8859-5",
	"ISO8859-6":       "ISO-8859-6",
	"CP1256":          "Windows-1256",
	"ISO8859-7":       "ISO-8859-7",
	"ISO8859-8":       "ISO-8859-8",
	"CP1255":          "Windows-1255",
	"ISO8859-9":       "ISO-8859-9",
	"ISO8859-10":      "ISO-8859-10",
	"ISO8859-11":      "ISO-8859-11",
	"CP874":           "Windows-874",
	"ISO8859-13":      "ISO-8859-13",
	"ISO8859-14":      "ISO-8859-14",
	"ISO8859-15":      "ISO-8859-15",
	"ISO8859-16":      "ISO-8859-16",
	"CP878":           "KOI8-R",
	"MacJapan":        "MacJapanese",
	"ASCII":           "US-ASCII",
	"ANSI_X3.4-1968":  "US-ASCII",
	"646":             "US-ASCII",
	"CP65000":         "UTF-7",
	"CP65001":         "UTF-8",
	"UTF-8-MAC":       "UTF8-MAC",
	"UTF-8-HFS":       "UTF8-MAC",
	"UCS-2BE":         "UTF-16BE",
	"UCS-4BE":         "UTF-32BE",
	"UCS-4LE":         "UTF-32LE",
	"CP932":           "Windows-31J",
	"csWindows31J":    "Windows-31J",
	"SJIS":            "Windows-31J",
	"PCK":             "Windows-31J",
	"CP1250":          "Windows-1250",
	"CP1251":          "Windows-1251",
	"CP1252":          "Windows-1252",
	"CP1253":          "Windows-1253",
	"CP1254":          "Windows-1254",
	"CP1257":          "Windows-1257",
	"locale":          "UTF-8",
	"external":        "UTF-8",
	"filesystem":      "UTF-8",
}
