package vm

import (
	"reflect"
	"testing"
)

// TestEmbeddedPreludeMatchesSource is the drift guard for the frozen prelude: the
// committed embeddedPrelude() (generated by `go generate` / cmd/freeze-prelude)
// must reconstruct exactly the ISeq the front-end produces from prelude.rb. If
// prelude.rb changes without regenerating, this fails — telling the developer to
// run `go generate ./internal/vm`. It is also the semantic proof that FreezeISeq
// round-trips real bytecode (constants, nested method/class bodies and all).
func TestEmbeddedPreludeMatchesSource(t *testing.T) {
	fresh, err := parseCompileFn(preludeSource)
	if err != nil {
		t.Fatalf("compiling prelude source: %v", err)
	}
	if !reflect.DeepEqual(fresh, embeddedPrelude()) {
		t.Fatal("embeddedPrelude() has drifted from prelude.rb; run `go generate ./internal/vm`")
	}
}
