//go:build rbgo_closed

package vm

// installPrelude loads the embedded-Ruby standard library from its frozen
// bytecode (embeddedProgram-style, generated by FreezeISeq). A closed-world
// binary links no front-end, so the prelude cannot be parsed at startup; running
// the pre-compiled ISeq gives the identical Comparable/Enumerable/… definitions.
func (vm *VM) installPrelude() {
	if _, err := vm.Run(embeddedPrelude()); err != nil {
		panic("vm: frozen prelude failed to load: " + err.Error())
	}
}
