# Generates internal/vm/grapheme_table.go with UAX#29 Grapheme_Cluster_Break
# property ranges + Extended_Pictographic ranges, sourced from the running
# Ruby's Unicode database so rbgo's segmenter matches MRI exactly.

MAX = 0x10FFFF

# GCB property enum order must match the Go constants.
GCB = %w[CR LF Control Extend ZWJ Regional_Indicator Prepend SpacingMark L V T LV LVT]
res = {}
GCB.each { |p| res[p] = Regexp.new("\\p{Grapheme_Cluster_Break=#{p}}") }

# Classify each codepoint into at most one GCB value (default "Other" omitted).
prop_of = Array.new(MAX + 1, nil)
(0..MAX).each do |cp|
  next if cp >= 0xD800 && cp <= 0xDFFF # surrogates: unassigned, skip
  ch = begin
    [cp].pack("U")
  rescue
    next
  end
  GCB.each do |p|
    if res[p].match?(ch)
      prop_of[cp] = p
      break
    end
  end
end

# Extended_Pictographic (independent of GCB value).
extpict_re = Regexp.new("\\p{Extended_Pictographic}")
extpict = Array.new(MAX + 1, false)
(0..MAX).each do |cp|
  next if cp >= 0xD800 && cp <= 0xDFFF
  ch = begin; [cp].pack("U"); rescue; next; end
  extpict[cp] = extpict_re.match?(ch)
end

def ranges(pred_arr)
  out = []
  lo = nil
  prev = nil
  (0..MAX).each do |cp|
    v = pred_arr[cp]
    if v
      if lo.nil?
        lo = cp
      end
    else
      if lo
        out << [lo, cp - 1]
        lo = nil
      end
    end
  end
  out << [lo, MAX] if lo
  out
end

# Build combined GCB range table sorted by lo.
gcb_ranges = []
GCB.each_with_index do |p, idx|
  pred = prop_of.map { |x| x == p }
  ranges(pred).each { |(lo, hi)| gcb_ranges << [lo, hi, idx] }
end
gcb_ranges.sort_by! { |r| r[0] }

extpict_ranges = ranges(extpict)

File.open(ARGV[0], "w") do |f|
  f.puts "// Copyright (c) the go-embedded-ruby/ruby authors"
  f.puts "//"
  f.puts "// SPDX-License-Identifier: BSD-3-Clause"
  f.puts
  f.puts "// Code generated by scripts/gen_gcb.rb from the Unicode database of"
  f.puts "// Ruby #{RUBY_VERSION}. DO NOT EDIT."
  f.puts
  f.puts "package vm"
  f.puts
  f.puts "// gcbProp is a Grapheme_Cluster_Break property value (UAX#29)."
  f.puts "type gcbProp uint8"
  f.puts
  f.puts "const ("
  f.puts "\tgcbOther gcbProp = iota"
  GCB.each { |p| f.puts "\tgcb#{p.gsub('_', '')}" }
  f.puts ")"
  f.puts
  f.puts "// gcbRange is a [lo, hi] codepoint span carrying a single GCB property."
  f.puts "type gcbRange struct {"
  f.puts "\tlo, hi rune"
  f.puts "\tprop   gcbProp"
  f.puts "}"
  f.puts
  f.puts "// gcbRanges holds every non-Other GCB span, sorted by lo for binary search."
  f.puts "var gcbRanges = []gcbRange{"
  gcb_ranges.each do |(lo, hi, idx)|
    name = "gcb#{GCB[idx].gsub('_', '')}"
    f.puts format("\t{0x%X, 0x%X, %s},", lo, hi, name)
  end
  f.puts "}"
  f.puts
  f.puts "// extPictRanges holds every Extended_Pictographic span, sorted by lo."
  f.puts "var extPictRanges = [][2]rune{"
  extpict_ranges.each do |(lo, hi)|
    f.puts format("\t{0x%X, 0x%X},", lo, hi)
  end
  f.puts "}"
end
puts "gcb ranges: #{gcb_ranges.size}, extpict ranges: #{extpict_ranges.size}"
