//go:build rbgo_closed && js && wasm

package main

import (
	"fmt"
	"os"

	"github.com/go-embedded-ruby/ruby/internal/vm"
)

// main runs the single program baked into this closed-world wasm binary, then
// blocks forever so the Go runtime stays alive for browser callbacks.
//
// Like the native closed main (closed_main.go) the program is embedded as
// bytecode by `rbgo build --closed --target wasm` (embeddedProgram, generated by
// FreezeISeq and injected via -overlay); no source file is read and no
// lexer/parser/compiler is linked. The program is free to use the interactive
// `JS` module (DOM/Canvas/events/JS.raf, see internal/vm/jsbridge_wasm.go),
// which vm.New registers automatically on wasm.
//
// After the program returns we do NOT exit: any JS event listeners or animation
// callbacks it registered must keep firing, and a Go wasm module that returns
// from main() is torn down. select{} parks the main goroutine indefinitely while
// the registered js.Func callbacks remain live (this mirrors cmd/wasm/main.go).
func main() {
	machine := vm.New(os.Stdout)
	if _, err := machine.Run(embeddedProgram()); err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
	select {} // keep the Go runtime alive so JS event/animation callbacks keep firing
}
